# Nextcloud Talk - Android Client
#
# SPDX-FileCopyrightText: 2017-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2024-2025 Marcel Hibbe <dev@mhibbe.de>
# SPDX-FileCopyrightText: 2021 Tim Krüger <t@timkrueger.me>
# SPDX-FileCopyrightText: 2017-2019 Mario Danic <mario@lovelyhq.com>
# SPDX-License-Identifier: GPL-3.0-or-later

# can be overriden by ~/.gradle/gradle.properties
NC_TEST_SERVER_BASEURL=http://server
NC_TEST_SERVER_USERNAME=test
NC_TEST_SERVER_PASSWORD=test
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
#android.debug.obsoleteApi=true


# JVM arguments to optimize heap usage, enable heap dump on out-of-memory errors, and set the file encoding
#org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
#org.gradle.dependency.verification.console=verbose
#kotlin.daemon.jvmargs=-Xmx6144m -XX:+UseParallelGC
#org.gradle.caching=true
#org.gradle.parallel=true
#org.gradle.configureondemand=true
#kapt.incremental.apt=true
#org.gradle.daemon=true
#org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=512m
org.gradle.dependency.verification.console=verbose
kotlin.daemon.jvmargs=-Xmx1g -XX:+UseG1GC
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
kapt.incremental.apt=true
org.gradle.daemon=true
org.gradle.configuration-cache=true

# Needed for local libs
# org.gradle.dependency.verification=lenient

# ??APMS(??gradle8.0??)
# Failed to apply plugin 'com.huawei.agconnect'.
#   > API 'android.registerTransform' is removed.
# https://developer.huawei.com/consumer/cn/doc/appgallery-connect-guides/agc-appmessaging-integratesdk-android-0000001072532718
# https://blog.csdn.net/weixin_44708240/article/details/130242646
apmsInstrumentationEnabled=false

android.injected.testOnly=false
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
